### This file needs to be run on an WSL2 env with ellyn (windows)!

In [1]:
from sklearn.datasets import load_wine # load_breast_cancer
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [2]:
data = load_wine()
X = data.data
y = data.target

In [3]:
print('y unique:', np.unique(y), '\n')

print('x:', X)

y unique: [0 1 2] 

x: [[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [4]:
le = LabelEncoder()
y_le = le.fit_transform(y)
print('yle unique:', np.unique(y_le))

yle unique: [0 1 2]


In [5]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from ellyn import ellyn

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2, random_state=42)

In [19]:
# Check all parameters here:
# https://github.com/cavalab/ellyn/blob/03ebdf07f0bfdca30da1a9a0a0da2989e9b1153c/src/ellyn.py#L42

e = ellyn(
    #g=200, 
    #popsize=50,
    verbosity=1,
    class_m4gp=True,
    op_list=['n','v','+','-','*','/', 'sin', 'cos', 'exp', 'log', 'sqrt'],
    #selection='lexicase',
    #fit_type='F1'
)

In [20]:
e.fit(X_train, y_train)

ellen_params: {'AR': False, 'AR_lookahead': False, 'AR_na': 1, 'AR_nb': 1, 'AR_nka': 1, 'AR_nkb': 0, 'ERC': True, 'ERCints': False, 'EstimateFitness': False, 'FE_ind_size': 0, 'FE_pop_size': 0, 'FE_rank': False, 'FE_train_gens': 0, 'FE_train_size': 0, 'G_sel': 1, 'G_shuffle': False, 'PS_sel': 1, 'SGD': False, 'align_dev': False, 'class_bool': False, 'class_m4gp': False, 'class_prune': False, 'classification': False, 'complex_measure': 1, 'cross': 3, 'cross_ar': 0.025, 'eHC_init': 0.5, 'eHC_its': 1, 'eHC_mut': False, 'eHC_on': False, 'eHC_prob': 0.1, 'eHC_slim': False, 'elitism': False, 'estimate_generality': False, 'fit_type': 'MSE', 'g': 100, 'init_trees': True, 'init_validate_on': False, 'island_gens': 100, 'islands': True, 'learning_rate': 1.0, 'lex_class': False, 'lex_eps_dynamic': False, 'lex_eps_dynamic_madcap': False, 'lex_eps_dynamic_rand': False, 'lex_eps_error': False, 'lex_eps_error_mad': False, 'lex_eps_global': False, 'lex_eps_std': False, 'lex_eps_target': False, 'lex_eps

ellyn(class_m4gp=True,
      op_list=['n', 'v', '+', '-', '*', '/', 'sin', 'cos', 'exp', 'log',
               'sqrt'],
      verbosity=1)

In [21]:
predictions = e.predict(X_test)

print(predictions)

[0 0 2 0 1 0 1 2 1 2 1 2 1 1 0 1 1 1 1 1 1 1 1 2 2 2 1 1 1 0 1 1 2 0 1 0]


In [22]:
# for ix, class_ in enumerate(predictions):
#     if class_ > 2:
#         predictions[ix]=2

print('M4GP:', accuracy_score(y_test, predictions))

M4GP: 0.8333333333333334


In [23]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

knn.fit(X_train, y_train)

KNeighborsClassifier()

In [24]:
print('KNN:', accuracy_score(y_test, knn.predict(X_test)))

KNN: 0.7222222222222222
